1. Create a null vector of size 10 but the fifth value which is 1.


In [1]:
import numpy as np

In [2]:
null_vector = np.zeros(10)

In [3]:
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2. Create a vector with values ranging from 10 to 49.


In [5]:
vectors=np.arange(10,49)
print(vectors)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
mat=np.arange(0,9)
print(mat)

[0 1 2 3 4 5 6 7 8]


In [16]:
arr=list(mat)

In [17]:
arr1=mat.reshape(3,3)
print(arr1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]


In [18]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero = np.nonzero(arr)

print(non_zero)


(array([0, 1, 4], dtype=int64),)


5. Create a 10x10 array with random values and find the minimum and maximum values.


In [30]:
arr1 = np.random.randint(0,500,100)
arr1

array([236, 418, 222, 208, 246, 270, 148, 109,  87, 462, 349, 303,  43,
       213, 177,  49,   0, 375, 200, 211,  34, 189, 407,  62, 427, 141,
       499,  82, 376,  48, 205, 499, 203,  80, 424, 203,  95, 297, 103,
       359, 421, 449, 249, 197, 314, 160, 231,  32,  91, 181, 467, 464,
       407, 251, 221,  42, 291, 120, 486, 499, 110, 442, 340, 494, 405,
       101, 270, 256, 191,  86, 124, 374, 273, 438, 191, 352, 175, 385,
       363,  25,  91, 224,  44, 349,  88, 489, 356, 294, 425, 401, 165,
       362, 191, 189,  51, 223, 308, 127,  94, 219])

In [31]:
arr2=arr1.reshape(10,10)
print(arr2)

[[236 418 222 208 246 270 148 109  87 462]
 [349 303  43 213 177  49   0 375 200 211]
 [ 34 189 407  62 427 141 499  82 376  48]
 [205 499 203  80 424 203  95 297 103 359]
 [421 449 249 197 314 160 231  32  91 181]
 [467 464 407 251 221  42 291 120 486 499]
 [110 442 340 494 405 101 270 256 191  86]
 [124 374 273 438 191 352 175 385 363  25]
 [ 91 224  44 349  88 489 356 294 425 401]
 [165 362 191 189  51 223 308 127  94 219]]


In [32]:
min_value = arr2.min()
max_value = arr2.max()

print("mininum:",min_value)
print("maxmiun",max_value)

mininum: 0
maxmiun 499


6. Create a random vector of size 30 and find the mean value.


In [33]:
vector=np.random.randint(0,100,30)
print(vector)

[72 44 58 54 42 77 81 60  3 87  5 89 76 51 35 29  2 54 98 88 37 56 34  4
 98 58 98 55 72 49]


In [34]:
np.mean(vector)

55.53333333333333

In [35]:
int(np.mean(vector))

55